// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHIXoZUZVQvO65ldn-lgBZDCTcuqBNEy8',
    appId: '1:560400509256:web:4a192d97956e808538ab7d',
    messagingSenderId: '560400509256',
    projectId: 'readingowl-ff5fa',
    authDomain: 'readingowl-ff5fa.firebaseapp.com',
    databaseURL: 'https://readingowl-ff5fa-default-rtdb.firebaseio.com',
    storageBucket: 'readingowl-ff5fa.appspot.com',
    measurementId: 'G-E9CVJL8JTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3tEOsURXpo1KRPAKgEBPxu-K9Wk7jMVM',
    appId: '1:560400509256:android:3ae3f8ecdf034b2c38ab7d',
    messagingSenderId: '560400509256',
    projectId: 'readingowl-ff5fa',
    databaseURL: 'https://readingowl-ff5fa-default-rtdb.firebaseio.com',
    storageBucket: 'readingowl-ff5fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA75x-94jyJz1kw37t3Lm7AZ2TH63ejKDI',
    appId: '1:560400509256:ios:38fc10655433445738ab7d',
    messagingSenderId: '560400509256',
    projectId: 'readingowl-ff5fa',
    databaseURL: 'https://readingowl-ff5fa-default-rtdb.firebaseio.com',
    storageBucket: 'readingowl-ff5fa.appspot.com',
    iosClientId: '560400509256-crhr48k3uu339p1nfc9q50ivakn912pp.apps.googleusercontent.com',
    iosBundleId: 'com.example.readingOwl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA75x-94jyJz1kw37t3Lm7AZ2TH63ejKDI',
    appId: '1:560400509256:ios:38fc10655433445738ab7d',
    messagingSenderId: '560400509256',
    projectId: 'readingowl-ff5fa',
    databaseURL: 'https://readingowl-ff5fa-default-rtdb.firebaseio.com',
    storageBucket: 'readingowl-ff5fa.appspot.com',
    iosClientId: '560400509256-crhr48k3uu339p1nfc9q50ivakn912pp.apps.googleusercontent.com',
    iosBundleId: 'com.example.readingOwl',
  );
}
