// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiHyGktG7D2yaywHkILMReCQg35xQ5J1c',
    appId: '1:172898981582:web:796cf00d4475b875c5229f',
    messagingSenderId: '172898981582',
    projectId: 'readingowl-v1-0',
    authDomain: 'readingowl-v1-0.firebaseapp.com',
    storageBucket: 'readingowl-v1-0.appspot.com',
    measurementId: 'G-BWBQMDS2CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4CHoOJrym7-NqjDPugHUZ7Vund47NNiY',
    appId: '1:172898981582:android:9a63b01208079435c5229f',
    messagingSenderId: '172898981582',
    projectId: 'readingowl-v1-0',
    storageBucket: 'readingowl-v1-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Iz7Mui_0gM60SGh9C5T3CsLCkIWCAEM',
    appId: '1:172898981582:ios:e445bc511073708ac5229f',
    messagingSenderId: '172898981582',
    projectId: 'readingowl-v1-0',
    storageBucket: 'readingowl-v1-0.appspot.com',
    iosClientId: '172898981582-pjk7hsj3dqs82pkafivoq7semd8plt56.apps.googleusercontent.com',
    iosBundleId: 'com.example.readingOwl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Iz7Mui_0gM60SGh9C5T3CsLCkIWCAEM',
    appId: '1:172898981582:ios:e445bc511073708ac5229f',
    messagingSenderId: '172898981582',
    projectId: 'readingowl-v1-0',
    storageBucket: 'readingowl-v1-0.appspot.com',
    iosClientId: '172898981582-pjk7hsj3dqs82pkafivoq7semd8plt56.apps.googleusercontent.com',
    iosBundleId: 'com.example.readingOwl',
  );
}
